In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('building-net.csv')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2683: DtypeWarning: Columns (5,11,14,15,19,20,23,24,25,28,29,31,34,35,36,38,39,40,42,43,44,45,46,47,48,50,51,52,53,54,55,56,59,61,62,63,65,66,67,68,69,70,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,112,113,115,116,117,119,120,121,122,123,124,125,127,128,129,130,131,132,133,134,135,136,137,138,139,140,142,143,144,145,146,147,148,149,150,151,152,153,154) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
data_part =data[['fishnet-ID', 'fishnet-area', 'bu-area']]

In [15]:
data_part = data_part.fillna(0)

In [16]:
#data_city_block = data[data['place']=='city_block']

In [17]:
#data_city_block.shape

In [18]:
data_fishnet = data_part.groupby(['fishnet-ID']).sum()

In [21]:
data_fishnet = data_fishnet.reset_index()

In [27]:
data_fishnet['building_density'] = data_fishnet['bu-area'] / 40000

In [29]:
data_fishnet.drop(['fishnet-area'], axis = 1)

      fishnet-ID  bu-area  building_density
0              1      0.0          0.000000
1              2      0.0          0.000000
2              3      0.0          0.000000
3              4      0.0          0.000000
4              5      0.0          0.000000
5              6      0.0          0.000000
6              7      0.0          0.000000
7              8      0.0          0.000000
8              9      0.0          0.000000
9             10      0.0          0.000000
10            11      0.0          0.000000
11            12      0.0          0.000000
12            13      0.0          0.000000
13            14      0.0          0.000000
14            15      0.0          0.000000
15            16      0.0          0.000000
16            17      0.0          0.000000
17            18      0.0          0.000000
18            19      0.0          0.000000
19            20      0.0          0.000000
20            21      0.0          0.000000
21            22      0.0          0.000000
22            23      0.0          0.000000
23            24      0.0          0.000000
24            25      0.0          0.000000
25            26      0.0          0.000000
26            27      0.0          0.000000
27            28      0.0          0.000000
28            29      0.0          0.000000
29            30      0.0          0.000000
...          ...      ...               ...
1490        1491      0.0          0.000000
1491        1492      0.0          0.000000
1492        1493      0.0          0.000000
1493        1494      0.0          0.000000
1494        1495      0.0          0.000000
1495        1496      0.0          0.000000
1496        1497      0.0          0.000000
1497        1498      0.0          0.000000
1498        1499      0.0          0.000000
1499        1500      0.0          0.000000
1500        1501      0.0          0.000000
1501        1502      0.0          0.000000
1502        1503      0.0          0.000000
1503        1504      0.0          0.000000
1504        1505      0.0          0.000000
1505        1506      0.0          0.000000
1506        1507      0.0          0.000000
1507        1508      0.0          0.000000
1508        1509    706.0          0.017650
1509        1510    203.0          0.005075
1510        1511      0.0          0.000000
1511        1512      0.0          0.000000
1512        1513      0.0          0.000000
1513        1514      0.0          0.000000
1514        1515      0.0          0.000000
1515        1516      0.0          0.000000
1516        1517      0.0          0.000000
1517        1518      0.0          0.000000
1518        1519      0.0          0.000000
1519        1520      0.0          0.000000

[1520 rows x 3 columns]

In [31]:
data_fishnet.to_csv('building_density.csv')